# Generated by Django 4.2.1 on 2023-05-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_middle_name_user_fill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fill_name',
            new_name='full_name',
        ),
    ]
