# Generated by Django 4.2.1 on 2023-05-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='AdjustmentWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('launch', models.CharField(choices=[('Перерыв 15 минут', 'Перерыв 15 минут'), ('Перерыв 30 минут', 'Перерыв 30 минут'), ('Без перерыва', 'Без перерыва'), ('Другое', 'Другое')], max_length=150)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timing_adjustment.shiftmanager')),
            ],
            options={
                'verbose_name': 'Корректировка рабочего времени',
                'verbose_name_plural': 'Корректировка рабочего времени',
            },
        ),
    ]
