# Generated by Django 4.2.1 on 2023-05-11 07:29

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Восересенье', 'Восересенье')], max_length=20)),
                ('shift_type', models.CharField(choices=[('FT', 'FT'), ('Первая смена', 'Первая смена'), ('Вторая смена', 'Вторая смена'), ('Выходной', 'Выходной'), ('Другое', 'Другое')], max_length=30)),
                ('custom_time', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('night', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
