# Generated by Django 4.2.1 on 2023-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0002_alter_temporary_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary',
            name='custom_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
