# Generated by Django 4.2.1 on 2023-05-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0003_alter_temporary_custom_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='wishes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
