# Generated by Django 4.2.1 on 2023-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0005_alter_temporary_custom_time_alter_temporary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary',
            name='wishes',
            field=models.TextField(blank=True, default=None),
        ),
    ]
