# Generated by Django 4.2.1 on 2023-05-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0009_alter_temporary_custom_time_alter_temporary_wishes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporary',
            options={'verbose_name': 'Временные', 'verbose_name_plural': 'Временные'},
        ),
    ]
