# Generated by Django 4.2.1 on 2023-05-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vakantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vakantie', models.CharField(choices=[('Трудовой(оплачиваемый)', 'Трудовой(оплачиваемый)'), ('Социальный(за свой счет)', 'Социальный(за свой счет)')], max_length=150)),
                ('start_vacation', models.DateTimeField()),
                ('end_vacation', models.DateTimeField()),
            ],
        ),
    ]
