# Generated by Django 4.2.1 on 2023-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakantie', '0003_alter_vakantie_end_vacation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vakantie',
            options={'verbose_name': 'Заявка на отпуск', 'verbose_name_plural': 'Заявка на отпуски'},
        ),
        migrations.AlterField(
            model_name='vakantie',
            name='end_vacation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
