# Generated by Django 4.2.1 on 2023-05-21 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vakantie', '0004_alter_vakantie_options_alter_vakantie_end_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakantie',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
