# Generated by Django 4.2.1 on 2023-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(choices=[('жалоба', 'жалоба'), ('Предложение/идея', 'Предложение/идея'), ('Похвала', 'Похвала'), ('Другое', 'Другое')], max_length=150)),
                ('team', models.CharField(choices=[('Весь управляющий состав (зам. директора и директор)', 'Весь управляющий состав (зам. директора и директор)'), ('Весь менеджерский состав', 'Весь менеджерский состав'), ('Весь состав тренеров', 'Весь состав тренеров'), ('Весь состав ЧК', 'Весь состав ЧК'), ('Всю команду', 'Всю команду'), ('Другое', 'Другое')], max_length=255)),
                ('situation', models.TextField()),
                ('other', models.TextField()),
            ],
        ),
    ]
