# Generated by Django 4.2.1 on 2023-05-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Заявка на отпуск', 'verbose_name_plural': 'Заявка на отпуски'},
        ),
    ]
