# Generated by Django 4.2.1 on 2023-05-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обрантая связь', 'verbose_name_plural': 'Обрантая связь'},
        ),
    ]
