# Generated by Django 4.2.1 on 2023-05-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='other',
            field=models.TextField(blank=True),
        ),
    ]
